services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "21370:21370"
    restart: always
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    volumes:
      - ./topsis_app:/app/topsis_app
      - ./app.py:/app/app.py

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - backend
